//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrediNET.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrediNET.Languages.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Balance : .
        /// </summary>
        internal static string Account_Balance {
            get {
                return ResourceManager.GetString("Account_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Balance of   /  /     : &amp;0.00.
        /// </summary>
        internal static string Account_BalanceDateZero {
            get {
                return ResourceManager.GetString("Account_BalanceDateZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Balance of .
        /// </summary>
        internal static string Account_BalanceOf {
            get {
                return ResourceManager.GetString("Account_BalanceOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Balance : &amp;0.00.
        /// </summary>
        internal static string Account_BalanceZero {
            get {
                return ResourceManager.GetString("Account_BalanceZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leave this field empty to keep current password.
        /// </summary>
        internal static string Account_Creation_LeaveEmpty {
            get {
                return ResourceManager.GetString("Account_Creation_LeaveEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please type the account&apos;s password below..
        /// </summary>
        internal static string Account_Crypted_TypePassword {
            get {
                return ResourceManager.GetString("Account_Crypted_TypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CrediNET Account (*.cna)|*.cna.
        /// </summary>
        internal static string Account_FileFilter {
            get {
                return ResourceManager.GetString("Account_FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CrediNET crypted Account (*.cne)|*.cne.
        /// </summary>
        internal static string Account_FileFilterCrypted {
            get {
                return ResourceManager.GetString("Account_FileFilterCrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CrediNET Account (*.cna)|*.cna|SQLite CrediNET Account (*.cnsql)|*.cnsql.
        /// </summary>
        internal static string Account_FileFilterSave {
            get {
                return ResourceManager.GetString("Account_FileFilterSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;No account loaded&gt;.
        /// </summary>
        internal static string Account_NoneLoaded {
            get {
                return ResourceManager.GetString("Account_NoneLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0.00.
        /// </summary>
        internal static string Account_TotalZero {
            get {
                return ResourceManager.GetString("Account_TotalZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afghan afghani.
        /// </summary>
        internal static string Currencies_AFA {
            get {
                return ResourceManager.GetString("Currencies_AFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Albanian lek.
        /// </summary>
        internal static string Currencies_ALL {
            get {
                return ResourceManager.GetString("Currencies_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Argentine peso.
        /// </summary>
        internal static string Currencies_ARS {
            get {
                return ResourceManager.GetString("Currencies_ARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Australian dollar.
        /// </summary>
        internal static string Currencies_AUD {
            get {
                return ResourceManager.GetString("Currencies_AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aruban florin.
        /// </summary>
        internal static string Currencies_AWG {
            get {
                return ResourceManager.GetString("Currencies_AWG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Barbadian Dollar.
        /// </summary>
        internal static string Currencies_BBD {
            get {
                return ResourceManager.GetString("Currencies_BBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bangladesh Taka.
        /// </summary>
        internal static string Currencies_BDT {
            get {
                return ResourceManager.GetString("Currencies_BDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bahraini dinar.
        /// </summary>
        internal static string Currencies_BHD {
            get {
                return ResourceManager.GetString("Currencies_BHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bermuda Dollar.
        /// </summary>
        internal static string Currencies_BMD {
            get {
                return ResourceManager.GetString("Currencies_BMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bahamian dollar.
        /// </summary>
        internal static string Currencies_BSD {
            get {
                return ResourceManager.GetString("Currencies_BSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Belize Dollar.
        /// </summary>
        internal static string Currencies_BZD {
            get {
                return ResourceManager.GetString("Currencies_BZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Algerian dinar.
        /// </summary>
        internal static string Currencies_DZD {
            get {
                return ResourceManager.GetString("Currencies_DZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Albanian lek.
        /// </summary>
        internal static string Currency_ {
            get {
                return ResourceManager.GetString("Currency_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afghan afghani.
        /// </summary>
        internal static string Currency_AFA {
            get {
                return ResourceManager.GetString("Currency_AFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Albanian lek.
        /// </summary>
        internal static string Currency_ALL {
            get {
                return ResourceManager.GetString("Currency_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Argentine peso.
        /// </summary>
        internal static string Currency_ARS {
            get {
                return ResourceManager.GetString("Currency_ARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Australian dollar.
        /// </summary>
        internal static string Currency_AUD {
            get {
                return ResourceManager.GetString("Currency_AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aruban florin.
        /// </summary>
        internal static string Currency_AWG {
            get {
                return ResourceManager.GetString("Currency_AWG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Barbadian Dollar.
        /// </summary>
        internal static string Currency_BBD {
            get {
                return ResourceManager.GetString("Currency_BBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bangladesh Taka.
        /// </summary>
        internal static string Currency_BDT {
            get {
                return ResourceManager.GetString("Currency_BDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bahraini dinar.
        /// </summary>
        internal static string Currency_BHD {
            get {
                return ResourceManager.GetString("Currency_BHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Burundi Franc.
        /// </summary>
        internal static string Currency_BIF {
            get {
                return ResourceManager.GetString("Currency_BIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bermuda Dollar.
        /// </summary>
        internal static string Currency_BMD {
            get {
                return ResourceManager.GetString("Currency_BMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brunei Dollar.
        /// </summary>
        internal static string Currency_BND {
            get {
                return ResourceManager.GetString("Currency_BND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bolivian Boliviano.
        /// </summary>
        internal static string Currency_BOB {
            get {
                return ResourceManager.GetString("Currency_BOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brazilian Real.
        /// </summary>
        internal static string Currency_BRL {
            get {
                return ResourceManager.GetString("Currency_BRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bahamian dollar.
        /// </summary>
        internal static string Currency_BSD {
            get {
                return ResourceManager.GetString("Currency_BSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bhutanese Ngultrum.
        /// </summary>
        internal static string Currency_BTN {
            get {
                return ResourceManager.GetString("Currency_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Botswana Pula.
        /// </summary>
        internal static string Currency_BWP {
            get {
                return ResourceManager.GetString("Currency_BWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Belize Dollar.
        /// </summary>
        internal static string Currency_BZD {
            get {
                return ResourceManager.GetString("Currency_BZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Canadian Dollar.
        /// </summary>
        internal static string Currency_CAD {
            get {
                return ResourceManager.GetString("Currency_CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chilean Peso.
        /// </summary>
        internal static string Currency_CLP {
            get {
                return ResourceManager.GetString("Currency_CLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chinese Yuan.
        /// </summary>
        internal static string Currency_CNY {
            get {
                return ResourceManager.GetString("Currency_CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Colombian Peso.
        /// </summary>
        internal static string Currency_COP {
            get {
                return ResourceManager.GetString("Currency_COP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Costa Rica Colòn.
        /// </summary>
        internal static string Currency_CRC {
            get {
                return ResourceManager.GetString("Currency_CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cuban Peso.
        /// </summary>
        internal static string Currency_CUP {
            get {
                return ResourceManager.GetString("Currency_CUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cape Verde Escudo.
        /// </summary>
        internal static string Currency_CVE {
            get {
                return ResourceManager.GetString("Currency_CVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cyprus Pound.
        /// </summary>
        internal static string Currency_CYP {
            get {
                return ResourceManager.GetString("Currency_CYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Czech Koruna.
        /// </summary>
        internal static string Currency_CZK {
            get {
                return ResourceManager.GetString("Currency_CZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Djiboutian Franc.
        /// </summary>
        internal static string Currency_DJF {
            get {
                return ResourceManager.GetString("Currency_DJF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Danish Krone.
        /// </summary>
        internal static string Currency_DKK {
            get {
                return ResourceManager.GetString("Currency_DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dominican Peso.
        /// </summary>
        internal static string Currency_DOP {
            get {
                return ResourceManager.GetString("Currency_DOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Algerian dinar.
        /// </summary>
        internal static string Currency_DZD {
            get {
                return ResourceManager.GetString("Currency_DZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Egyptian Pound.
        /// </summary>
        internal static string Currency_EGP {
            get {
                return ResourceManager.GetString("Currency_EGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ethiopian Birr.
        /// </summary>
        internal static string Currency_ETB {
            get {
                return ResourceManager.GetString("Currency_ETB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Euro.
        /// </summary>
        internal static string Currency_EUR {
            get {
                return ResourceManager.GetString("Currency_EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Falkland Islands Pound.
        /// </summary>
        internal static string Currency_FKP {
            get {
                return ResourceManager.GetString("Currency_FKP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à British Pound.
        /// </summary>
        internal static string Currency_GBP {
            get {
                return ResourceManager.GetString("Currency_GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ghanian Cedi.
        /// </summary>
        internal static string Currency_GHC {
            get {
                return ResourceManager.GetString("Currency_GHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gibraltar Pound.
        /// </summary>
        internal static string Currency_GIP {
            get {
                return ResourceManager.GetString("Currency_GIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gambian Dalasi.
        /// </summary>
        internal static string Currency_GMD {
            get {
                return ResourceManager.GetString("Currency_GMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guinean Franc.
        /// </summary>
        internal static string Currency_GNF {
            get {
                return ResourceManager.GetString("Currency_GNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guatemalan Quetzal.
        /// </summary>
        internal static string Currency_GTQ {
            get {
                return ResourceManager.GetString("Currency_GTQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guyana Dollar.
        /// </summary>
        internal static string Currency_GYD {
            get {
                return ResourceManager.GetString("Currency_GYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hong Kong Dollar.
        /// </summary>
        internal static string Currency_HKD {
            get {
                return ResourceManager.GetString("Currency_HKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Honduran Lempira.
        /// </summary>
        internal static string Currency_HNL {
            get {
                return ResourceManager.GetString("Currency_HNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Croatian Kuna.
        /// </summary>
        internal static string Currency_HRK {
            get {
                return ResourceManager.GetString("Currency_HRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Haitian Gourde.
        /// </summary>
        internal static string Currency_HTG {
            get {
                return ResourceManager.GetString("Currency_HTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hungarian Forint.
        /// </summary>
        internal static string Currency_HUF {
            get {
                return ResourceManager.GetString("Currency_HUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indonesian Rupiah.
        /// </summary>
        internal static string Currency_IDR {
            get {
                return ResourceManager.GetString("Currency_IDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Israeli Shekel.
        /// </summary>
        internal static string Currency_ILS {
            get {
                return ResourceManager.GetString("Currency_ILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indian Rupee.
        /// </summary>
        internal static string Currency_INR {
            get {
                return ResourceManager.GetString("Currency_INR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Iraqi Dinar.
        /// </summary>
        internal static string Currency_IQD {
            get {
                return ResourceManager.GetString("Currency_IQD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Icelandic Króna.
        /// </summary>
        internal static string Currency_ISK {
            get {
                return ResourceManager.GetString("Currency_ISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jamaican Dollar.
        /// </summary>
        internal static string Currency_JMD {
            get {
                return ResourceManager.GetString("Currency_JMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jordanian Dinar.
        /// </summary>
        internal static string Currency_JOD {
            get {
                return ResourceManager.GetString("Currency_JOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Japanese Yen.
        /// </summary>
        internal static string Currency_JPY {
            get {
                return ResourceManager.GetString("Currency_JPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kenyan Shilling.
        /// </summary>
        internal static string Currency_KES {
            get {
                return ResourceManager.GetString("Currency_KES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cambodia Riel.
        /// </summary>
        internal static string Currency_KHR {
            get {
                return ResourceManager.GetString("Currency_KHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comoros Franc.
        /// </summary>
        internal static string Currency_KMF {
            get {
                return ResourceManager.GetString("Currency_KMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à South Korean Won.
        /// </summary>
        internal static string Currency_KRW {
            get {
                return ResourceManager.GetString("Currency_KRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kuwaiti Dinar.
        /// </summary>
        internal static string Currency_KWD {
            get {
                return ResourceManager.GetString("Currency_KWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cayman Islands Dollar.
        /// </summary>
        internal static string Currency_KYD {
            get {
                return ResourceManager.GetString("Currency_KYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kazakhstani Tenge.
        /// </summary>
        internal static string Currency_KZT {
            get {
                return ResourceManager.GetString("Currency_KZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lao Kip.
        /// </summary>
        internal static string Currency_LAK {
            get {
                return ResourceManager.GetString("Currency_LAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lebanese Pound.
        /// </summary>
        internal static string Currency_LBP {
            get {
                return ResourceManager.GetString("Currency_LBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lesotho Loti.
        /// </summary>
        internal static string Currency_LSL {
            get {
                return ResourceManager.GetString("Currency_LSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à El Salvador Colòn.
        /// </summary>
        internal static string Currency_SVC {
            get {
                return ResourceManager.GetString("Currency_SVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CFA Franc (BEAC).
        /// </summary>
        internal static string Currency_XAF {
            get {
                return ResourceManager.GetString("Currency_XAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à East Caribbean Dollar.
        /// </summary>
        internal static string Currency_XCD {
            get {
                return ResourceManager.GetString("Currency_XCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CFA Franc (BCEAO).
        /// </summary>
        internal static string Currency_XOF {
            get {
                return ResourceManager.GetString("Currency_XOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit operation.
        /// </summary>
        internal static string Operation_Edit {
            get {
                return ResourceManager.GetString("Operation_Edit", resourceCulture);
            }
        }
    }
}
