//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrediNET.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrediNET.Languages.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Balance : .
        /// </summary>
        internal static string Account_Balance {
            get {
                return ResourceManager.GetString("Account_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Balance of   /  /     : &amp;0.00.
        /// </summary>
        internal static string Account_BalanceDateZero {
            get {
                return ResourceManager.GetString("Account_BalanceDateZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Balance of .
        /// </summary>
        internal static string Account_BalanceOf {
            get {
                return ResourceManager.GetString("Account_BalanceOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Balance : &amp;0.00.
        /// </summary>
        internal static string Account_BalanceZero {
            get {
                return ResourceManager.GetString("Account_BalanceZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leave this field empty to keep current password.
        /// </summary>
        internal static string Account_Creation_LeaveEmpty {
            get {
                return ResourceManager.GetString("Account_Creation_LeaveEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please type the account&apos;s password below..
        /// </summary>
        internal static string Account_Crypted_TypePassword {
            get {
                return ResourceManager.GetString("Account_Crypted_TypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CrediNET Account (*.cna)|*.cna.
        /// </summary>
        internal static string Account_FileFilter {
            get {
                return ResourceManager.GetString("Account_FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CrediNET crypted Account (*.cne)|*.cne.
        /// </summary>
        internal static string Account_FileFilterCrypted {
            get {
                return ResourceManager.GetString("Account_FileFilterCrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CrediNET Account (*.cna)|*.cna|SQLite CrediNET Account (*.cnsql)|*.cnsql.
        /// </summary>
        internal static string Account_FileFilterSave {
            get {
                return ResourceManager.GetString("Account_FileFilterSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;No account loaded&gt;.
        /// </summary>
        internal static string Account_NoneLoaded {
            get {
                return ResourceManager.GetString("Account_NoneLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0.00.
        /// </summary>
        internal static string Account_TotalZero {
            get {
                return ResourceManager.GetString("Account_TotalZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à United Arab Emirates dirham.
        /// </summary>
        internal static string Currency_AED {
            get {
                return ResourceManager.GetString("Currency_AED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afghan afghani.
        /// </summary>
        internal static string Currency_AFA {
            get {
                return ResourceManager.GetString("Currency_AFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Albanian lek.
        /// </summary>
        internal static string Currency_ALL {
            get {
                return ResourceManager.GetString("Currency_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Netherlands Antillean Guilder.
        /// </summary>
        internal static string Currency_ANG {
            get {
                return ResourceManager.GetString("Currency_ANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Argentine peso.
        /// </summary>
        internal static string Currency_ARS {
            get {
                return ResourceManager.GetString("Currency_ARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Australian dollar.
        /// </summary>
        internal static string Currency_AUD {
            get {
                return ResourceManager.GetString("Currency_AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aruban florin.
        /// </summary>
        internal static string Currency_AWG {
            get {
                return ResourceManager.GetString("Currency_AWG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Barbadian Dollar.
        /// </summary>
        internal static string Currency_BBD {
            get {
                return ResourceManager.GetString("Currency_BBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bangladesh Taka.
        /// </summary>
        internal static string Currency_BDT {
            get {
                return ResourceManager.GetString("Currency_BDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bahraini dinar.
        /// </summary>
        internal static string Currency_BHD {
            get {
                return ResourceManager.GetString("Currency_BHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Burundi Franc.
        /// </summary>
        internal static string Currency_BIF {
            get {
                return ResourceManager.GetString("Currency_BIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bermuda Dollar.
        /// </summary>
        internal static string Currency_BMD {
            get {
                return ResourceManager.GetString("Currency_BMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brunei Dollar.
        /// </summary>
        internal static string Currency_BND {
            get {
                return ResourceManager.GetString("Currency_BND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bolivian Boliviano.
        /// </summary>
        internal static string Currency_BOB {
            get {
                return ResourceManager.GetString("Currency_BOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brazilian Real.
        /// </summary>
        internal static string Currency_BRL {
            get {
                return ResourceManager.GetString("Currency_BRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bahamian dollar.
        /// </summary>
        internal static string Currency_BSD {
            get {
                return ResourceManager.GetString("Currency_BSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bhutanese Ngultrum.
        /// </summary>
        internal static string Currency_BTN {
            get {
                return ResourceManager.GetString("Currency_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Botswana Pula.
        /// </summary>
        internal static string Currency_BWP {
            get {
                return ResourceManager.GetString("Currency_BWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Belize Dollar.
        /// </summary>
        internal static string Currency_BZD {
            get {
                return ResourceManager.GetString("Currency_BZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Canadian Dollar.
        /// </summary>
        internal static string Currency_CAD {
            get {
                return ResourceManager.GetString("Currency_CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Swiss Franc.
        /// </summary>
        internal static string Currency_CHF {
            get {
                return ResourceManager.GetString("Currency_CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chilean Peso.
        /// </summary>
        internal static string Currency_CLP {
            get {
                return ResourceManager.GetString("Currency_CLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chinese Yuan.
        /// </summary>
        internal static string Currency_CNY {
            get {
                return ResourceManager.GetString("Currency_CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Colombian Peso.
        /// </summary>
        internal static string Currency_COP {
            get {
                return ResourceManager.GetString("Currency_COP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Costa Rica Colòn.
        /// </summary>
        internal static string Currency_CRC {
            get {
                return ResourceManager.GetString("Currency_CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cuban Peso.
        /// </summary>
        internal static string Currency_CUP {
            get {
                return ResourceManager.GetString("Currency_CUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cape Verde Escudo.
        /// </summary>
        internal static string Currency_CVE {
            get {
                return ResourceManager.GetString("Currency_CVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cyprus Pound.
        /// </summary>
        internal static string Currency_CYP {
            get {
                return ResourceManager.GetString("Currency_CYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Czech Koruna.
        /// </summary>
        internal static string Currency_CZK {
            get {
                return ResourceManager.GetString("Currency_CZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Djiboutian Franc.
        /// </summary>
        internal static string Currency_DJF {
            get {
                return ResourceManager.GetString("Currency_DJF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Danish Krone.
        /// </summary>
        internal static string Currency_DKK {
            get {
                return ResourceManager.GetString("Currency_DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dominican Peso.
        /// </summary>
        internal static string Currency_DOP {
            get {
                return ResourceManager.GetString("Currency_DOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Algerian dinar.
        /// </summary>
        internal static string Currency_DZD {
            get {
                return ResourceManager.GetString("Currency_DZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Egyptian Pound.
        /// </summary>
        internal static string Currency_EGP {
            get {
                return ResourceManager.GetString("Currency_EGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ethiopian Birr.
        /// </summary>
        internal static string Currency_ETB {
            get {
                return ResourceManager.GetString("Currency_ETB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Euro.
        /// </summary>
        internal static string Currency_EUR {
            get {
                return ResourceManager.GetString("Currency_EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Falkland Islands Pound.
        /// </summary>
        internal static string Currency_FKP {
            get {
                return ResourceManager.GetString("Currency_FKP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à British Pound.
        /// </summary>
        internal static string Currency_GBP {
            get {
                return ResourceManager.GetString("Currency_GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ghanian Cedi.
        /// </summary>
        internal static string Currency_GHC {
            get {
                return ResourceManager.GetString("Currency_GHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gibraltar Pound.
        /// </summary>
        internal static string Currency_GIP {
            get {
                return ResourceManager.GetString("Currency_GIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gambian Dalasi.
        /// </summary>
        internal static string Currency_GMD {
            get {
                return ResourceManager.GetString("Currency_GMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guinean Franc.
        /// </summary>
        internal static string Currency_GNF {
            get {
                return ResourceManager.GetString("Currency_GNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guatemalan Quetzal.
        /// </summary>
        internal static string Currency_GTQ {
            get {
                return ResourceManager.GetString("Currency_GTQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guyana Dollar.
        /// </summary>
        internal static string Currency_GYD {
            get {
                return ResourceManager.GetString("Currency_GYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hong Kong Dollar.
        /// </summary>
        internal static string Currency_HKD {
            get {
                return ResourceManager.GetString("Currency_HKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Honduran Lempira.
        /// </summary>
        internal static string Currency_HNL {
            get {
                return ResourceManager.GetString("Currency_HNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Croatian Kuna.
        /// </summary>
        internal static string Currency_HRK {
            get {
                return ResourceManager.GetString("Currency_HRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Haitian Gourde.
        /// </summary>
        internal static string Currency_HTG {
            get {
                return ResourceManager.GetString("Currency_HTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hungarian Forint.
        /// </summary>
        internal static string Currency_HUF {
            get {
                return ResourceManager.GetString("Currency_HUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indonesian Rupiah.
        /// </summary>
        internal static string Currency_IDR {
            get {
                return ResourceManager.GetString("Currency_IDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Israeli Shekel.
        /// </summary>
        internal static string Currency_ILS {
            get {
                return ResourceManager.GetString("Currency_ILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indian Rupee.
        /// </summary>
        internal static string Currency_INR {
            get {
                return ResourceManager.GetString("Currency_INR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Iraqi Dinar.
        /// </summary>
        internal static string Currency_IQD {
            get {
                return ResourceManager.GetString("Currency_IQD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Icelandic Króna.
        /// </summary>
        internal static string Currency_ISK {
            get {
                return ResourceManager.GetString("Currency_ISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jamaican Dollar.
        /// </summary>
        internal static string Currency_JMD {
            get {
                return ResourceManager.GetString("Currency_JMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jordanian Dinar.
        /// </summary>
        internal static string Currency_JOD {
            get {
                return ResourceManager.GetString("Currency_JOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Japanese Yen.
        /// </summary>
        internal static string Currency_JPY {
            get {
                return ResourceManager.GetString("Currency_JPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kenyan Shilling.
        /// </summary>
        internal static string Currency_KES {
            get {
                return ResourceManager.GetString("Currency_KES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cambodia Riel.
        /// </summary>
        internal static string Currency_KHR {
            get {
                return ResourceManager.GetString("Currency_KHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comoros Franc.
        /// </summary>
        internal static string Currency_KMF {
            get {
                return ResourceManager.GetString("Currency_KMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à North Korean Won.
        /// </summary>
        internal static string Currency_KPW {
            get {
                return ResourceManager.GetString("Currency_KPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à South Korean Won.
        /// </summary>
        internal static string Currency_KRW {
            get {
                return ResourceManager.GetString("Currency_KRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kuwaiti Dinar.
        /// </summary>
        internal static string Currency_KWD {
            get {
                return ResourceManager.GetString("Currency_KWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cayman Islands Dollar.
        /// </summary>
        internal static string Currency_KYD {
            get {
                return ResourceManager.GetString("Currency_KYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kazakhstani Tenge.
        /// </summary>
        internal static string Currency_KZT {
            get {
                return ResourceManager.GetString("Currency_KZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lao Kip.
        /// </summary>
        internal static string Currency_LAK {
            get {
                return ResourceManager.GetString("Currency_LAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lebanese Pound.
        /// </summary>
        internal static string Currency_LBP {
            get {
                return ResourceManager.GetString("Currency_LBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sri Lankan Rupee.
        /// </summary>
        internal static string Currency_LKR {
            get {
                return ResourceManager.GetString("Currency_LKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liberian Dollar.
        /// </summary>
        internal static string Currency_LRD {
            get {
                return ResourceManager.GetString("Currency_LRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lesotho Loti.
        /// </summary>
        internal static string Currency_LSL {
            get {
                return ResourceManager.GetString("Currency_LSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lithuanian Lita.
        /// </summary>
        internal static string Currency_LTL {
            get {
                return ResourceManager.GetString("Currency_LTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libyan Dinar.
        /// </summary>
        internal static string Currency_LYD {
            get {
                return ResourceManager.GetString("Currency_LYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moroccan Dirham.
        /// </summary>
        internal static string Currency_MAD {
            get {
                return ResourceManager.GetString("Currency_MAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moldovan Leu.
        /// </summary>
        internal static string Currency_MDL {
            get {
                return ResourceManager.GetString("Currency_MDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Macedonian Denar.
        /// </summary>
        internal static string Currency_MKD {
            get {
                return ResourceManager.GetString("Currency_MKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Myanmar Kyat.
        /// </summary>
        internal static string Currency_MMK {
            get {
                return ResourceManager.GetString("Currency_MMK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mongolian Tugrik.
        /// </summary>
        internal static string Currency_MNT {
            get {
                return ResourceManager.GetString("Currency_MNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Macanese Pataca.
        /// </summary>
        internal static string Currency_MOP {
            get {
                return ResourceManager.GetString("Currency_MOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mauritania Ouguiya.
        /// </summary>
        internal static string Currency_MRO {
            get {
                return ResourceManager.GetString("Currency_MRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maltese Lira.
        /// </summary>
        internal static string Currency_MTL {
            get {
                return ResourceManager.GetString("Currency_MTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mauritian Rupee.
        /// </summary>
        internal static string Currency_MUR {
            get {
                return ResourceManager.GetString("Currency_MUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maldives Rufiyaa.
        /// </summary>
        internal static string Currency_MVR {
            get {
                return ResourceManager.GetString("Currency_MVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Malawian Kwacha.
        /// </summary>
        internal static string Currency_MWK {
            get {
                return ResourceManager.GetString("Currency_MWK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mexican Peso.
        /// </summary>
        internal static string Currency_MXN {
            get {
                return ResourceManager.GetString("Currency_MXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Malaysian Ringgit.
        /// </summary>
        internal static string Currency_MYR {
            get {
                return ResourceManager.GetString("Currency_MYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mozambique Metical.
        /// </summary>
        internal static string Currency_MZM {
            get {
                return ResourceManager.GetString("Currency_MZM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Namibian Dollar.
        /// </summary>
        internal static string Currency_NAD {
            get {
                return ResourceManager.GetString("Currency_NAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nigerian Naira.
        /// </summary>
        internal static string Currency_NGN {
            get {
                return ResourceManager.GetString("Currency_NGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nicaragua Cordoba.
        /// </summary>
        internal static string Currency_NIO {
            get {
                return ResourceManager.GetString("Currency_NIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Norwegian Krone.
        /// </summary>
        internal static string Currency_NOK {
            get {
                return ResourceManager.GetString("Currency_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nepalese Rupee.
        /// </summary>
        internal static string Currency_NPR {
            get {
                return ResourceManager.GetString("Currency_NPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Zealand Dollar.
        /// </summary>
        internal static string Currency_NZD {
            get {
                return ResourceManager.GetString("Currency_NZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Omani Rial.
        /// </summary>
        internal static string Currency_OMR {
            get {
                return ResourceManager.GetString("Currency_OMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Panamanian Balboa.
        /// </summary>
        internal static string Currency_PAB {
            get {
                return ResourceManager.GetString("Currency_PAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Peruvian Nuevo Sol.
        /// </summary>
        internal static string Currency_PEN {
            get {
                return ResourceManager.GetString("Currency_PEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Papua New Guinean Kina.
        /// </summary>
        internal static string Currency_PGK {
            get {
                return ResourceManager.GetString("Currency_PGK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Philippine Peso.
        /// </summary>
        internal static string Currency_PHP {
            get {
                return ResourceManager.GetString("Currency_PHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pakistani Rupee.
        /// </summary>
        internal static string Currency_PKR {
            get {
                return ResourceManager.GetString("Currency_PKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Polish Zloty.
        /// </summary>
        internal static string Currency_PLN {
            get {
                return ResourceManager.GetString("Currency_PLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paraguayan Guaraní.
        /// </summary>
        internal static string Currency_PYG {
            get {
                return ResourceManager.GetString("Currency_PYG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qatari Riyal.
        /// </summary>
        internal static string Currency_QAR {
            get {
                return ResourceManager.GetString("Currency_QAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Romanian Leu.
        /// </summary>
        internal static string Currency_ROL {
            get {
                return ResourceManager.GetString("Currency_ROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Russian Rouble.
        /// </summary>
        internal static string Currency_RUB {
            get {
                return ResourceManager.GetString("Currency_RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saudi riyal.
        /// </summary>
        internal static string Currency_SAR {
            get {
                return ResourceManager.GetString("Currency_SAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Solomon Islands Dollar.
        /// </summary>
        internal static string Currency_SBD {
            get {
                return ResourceManager.GetString("Currency_SBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seychellois rupee.
        /// </summary>
        internal static string Currency_SCR {
            get {
                return ResourceManager.GetString("Currency_SCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sudanese Dinar.
        /// </summary>
        internal static string Currency_SDD {
            get {
                return ResourceManager.GetString("Currency_SDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Swedish Krona.
        /// </summary>
        internal static string Currency_SEK {
            get {
                return ResourceManager.GetString("Currency_SEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Singapore Dollar.
        /// </summary>
        internal static string Currency_SGD {
            get {
                return ResourceManager.GetString("Currency_SGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saint Helena Pound.
        /// </summary>
        internal static string Currency_SHP {
            get {
                return ResourceManager.GetString("Currency_SHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slovak Koruna.
        /// </summary>
        internal static string Currency_SKK {
            get {
                return ResourceManager.GetString("Currency_SKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sierra Leonean leone.
        /// </summary>
        internal static string Currency_SLL {
            get {
                return ResourceManager.GetString("Currency_SLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Somali Shilling.
        /// </summary>
        internal static string Currency_SOS {
            get {
                return ResourceManager.GetString("Currency_SOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Surinam Guilder.
        /// </summary>
        internal static string Currency_SRG {
            get {
                return ResourceManager.GetString("Currency_SRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à São Tomé and Príncipe dobra.
        /// </summary>
        internal static string Currency_STD {
            get {
                return ResourceManager.GetString("Currency_STD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à El Salvador Colòn.
        /// </summary>
        internal static string Currency_SVC {
            get {
                return ResourceManager.GetString("Currency_SVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Syrian Pound.
        /// </summary>
        internal static string Currency_SYP {
            get {
                return ResourceManager.GetString("Currency_SYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Swaziland Lilangeni.
        /// </summary>
        internal static string Currency_SZL {
            get {
                return ResourceManager.GetString("Currency_SZL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thai Baht.
        /// </summary>
        internal static string Currency_THB {
            get {
                return ResourceManager.GetString("Currency_THB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tunisian Dinar.
        /// </summary>
        internal static string Currency_TND {
            get {
                return ResourceManager.GetString("Currency_TND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tongan paʻanga.
        /// </summary>
        internal static string Currency_TOP {
            get {
                return ResourceManager.GetString("Currency_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Turkish lira.
        /// </summary>
        internal static string Currency_TRY {
            get {
                return ResourceManager.GetString("Currency_TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trinidad &amp; Tobago Dollar.
        /// </summary>
        internal static string Currency_TTD {
            get {
                return ResourceManager.GetString("Currency_TTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taiwan Dollar.
        /// </summary>
        internal static string Currency_TWD {
            get {
                return ResourceManager.GetString("Currency_TWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tanzanian Shilling.
        /// </summary>
        internal static string Currency_TZS {
            get {
                return ResourceManager.GetString("Currency_TZS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ukraine Hryvnia.
        /// </summary>
        internal static string Currency_UAH {
            get {
                return ResourceManager.GetString("Currency_UAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ugandan Shilling.
        /// </summary>
        internal static string Currency_UGX {
            get {
                return ResourceManager.GetString("Currency_UGX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à U.S. Dollar.
        /// </summary>
        internal static string Currency_USD {
            get {
                return ResourceManager.GetString("Currency_USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Uruguayan New Peso.
        /// </summary>
        internal static string Currency_UYU {
            get {
                return ResourceManager.GetString("Currency_UYU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Venezuelan Bolivar.
        /// </summary>
        internal static string Currency_VEB {
            get {
                return ResourceManager.GetString("Currency_VEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vietnamese dong.
        /// </summary>
        internal static string Currency_VND {
            get {
                return ResourceManager.GetString("Currency_VND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vanuatu Vatu.
        /// </summary>
        internal static string Currency_VUV {
            get {
                return ResourceManager.GetString("Currency_VUV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Samoan tālā.
        /// </summary>
        internal static string Currency_WST {
            get {
                return ResourceManager.GetString("Currency_WST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CFA Franc (BEAC).
        /// </summary>
        internal static string Currency_XAF {
            get {
                return ResourceManager.GetString("Currency_XAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à East Caribbean Dollar.
        /// </summary>
        internal static string Currency_XCD {
            get {
                return ResourceManager.GetString("Currency_XCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CFA Franc (BCEAO).
        /// </summary>
        internal static string Currency_XOF {
            get {
                return ResourceManager.GetString("Currency_XOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pacific Franc.
        /// </summary>
        internal static string Currency_XPF {
            get {
                return ResourceManager.GetString("Currency_XPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yemeni Riyal.
        /// </summary>
        internal static string Currency_YER {
            get {
                return ResourceManager.GetString("Currency_YER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à South African Rand.
        /// </summary>
        internal static string Currency_ZAR {
            get {
                return ResourceManager.GetString("Currency_ZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zambian Kwacha.
        /// </summary>
        internal static string Currency_ZMK {
            get {
                return ResourceManager.GetString("Currency_ZMK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zimbabwe Dollar.
        /// </summary>
        internal static string Currency_ZWD {
            get {
                return ResourceManager.GetString("Currency_ZWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit operation.
        /// </summary>
        internal static string Operation_Edit {
            get {
                return ResourceManager.GetString("Operation_Edit", resourceCulture);
            }
        }
    }
}
