//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrediNET.Languages {
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class vi_VN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal vi_VN() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrediNET.Languages.vi-VN", typeof(vi_VN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Số dư : .
        /// </summary>
        internal static string Account_Balance {
            get {
                return ResourceManager.GetString("Account_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Số dư ngày   /  /     : 0,00 .
        /// </summary>
        internal static string Account_BalanceDateZero {
            get {
                return ResourceManager.GetString("Account_BalanceDateZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Số dư của ngày .
        /// </summary>
        internal static string Account_BalanceOf {
            get {
                return ResourceManager.GetString("Account_BalanceOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Số dư : 0,00 .
        /// </summary>
        internal static string Account_BalanceZero {
            get {
                return ResourceManager.GetString("Account_BalanceZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Để trống ô này để giữ lại mật khẩu hiện tại.
        /// </summary>
        internal static string Account_Creation_LeaveEmpty {
            get {
                return ResourceManager.GetString("Account_Creation_LeaveEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Làm ơn nhập vào mật khẩu cho tài khoản..
        /// </summary>
        internal static string Account_Crypted_TypePassword {
            get {
                return ResourceManager.GetString("Account_Crypted_TypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tài khoản CrediNET (*.cna)|*.cna.
        /// </summary>
        internal static string Account_FileFilter {
            get {
                return ResourceManager.GetString("Account_FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tài khoản CrediNET mã hóa (*.cne)|*.cne.
        /// </summary>
        internal static string Account_FileFilterCrypted {
            get {
                return ResourceManager.GetString("Account_FileFilterCrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tài khoản CrediNET (*.cna)|*.cna|Tài khoản CrediNET SQLite (*.cnsql)|*.cnsql.
        /// </summary>
        internal static string Account_FileFilterSave {
            get {
                return ResourceManager.GetString("Account_FileFilterSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;Chưa đăng nhập tài khoản&gt;.
        /// </summary>
        internal static string Account_NoneLoaded {
            get {
                return ResourceManager.GetString("Account_NoneLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chỉnh sửa hoạt động.
        /// </summary>
        internal static string Operation_Edit {
            get {
                return ResourceManager.GetString("Operation_Edit", resourceCulture);
            }
        }
    }
}
